test_filename: '../../Data/test_data.csv'
type2label: '../../Data/type2label_all.json'
epochs: 50
pretrained_model: 'microsoft/graphcodebert-base'
do_train: false
do_eval: false
do_test: true
model_type: 'roberta'
model_name_or_path: 'microsoft/graphcodebert-base'
tokenizer_name: 'microsoft/graphcodebert-base'
config_name: 'microsoft/graphcodebert-base'
max_source_length: 448
max_target_length: 448
data_flow_length: 64
beam_size: 10
gradient_accumulation_steps: 4
train_batch_size: 32
eval_batch_size: 64
learning_rate: 1.0e-4
num_train_epochs: 50
use_awl: false
num_labels: 17
cls_dropout_prob: 0.1
load_model_path: 'saved_models/checkpoint-best-f1/pytorch_model.bin'
